site_name: Matriculaí
nav:
  - Home: 'index.md'
  - Visão de produto e projeto: 
    - Visão de produto: 'visao_produto.md'
    - Visão de projeto: 'visao_projeto.md'
    - Processos de desenvolvimento de software: 'desenvolvimento.md'
  - Sprints: 'sprints.md'
  - Backlog: 'backlog.md'
  - Design: 
      - Arquitetura: 'arquitetura.md'
      - Padrões de interface: 'padroes.md'
  - Lições Aprendidas: 'licoes.md'
  - Entregas: 
    - Unidade 1: 'unidade1.md'
    - Unidade 2: 'unidade2.md'
    - Unidade 3: 'unidade3.md'
    - Unidade 4: 'unidade4.md'
  - Exercícios: 
      - Exercícios Cruzados: 'exercicios_cruzados.md'
      - Exercícios da Equipe: 'exercicio_nosso.md'
  - Testes:
      - MVP 1: 'mvp1.md'
      - MVP 2: 'mvp2.md'

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: #606CF5
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: #606CF5
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra_css:
  - stylesheets/extra.css
extra:
  generator: false