site_name: Matriculaí
nav:
  - Home: 'index.md'
  - Visão de Produto: 'visao_produto.md'
  - Visão de Projeto: 'visao_projeto.md'
  - Sprints: 'sprints.md'
  - Entregas: 'entregas.md'
  - Lições Aprendidas: 'licoes.md'

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: #606CF5
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: #606CF5
      toggle:
        icon: material/weather-sunny
        name: Modo claro
extra_css:
  - stylesheets/extra.css
extra:
  generator: false